# ---
kind: pipeline
type: docker
name: default
when: 
 event: [ tag ]
 branch: [ develop ]
volumes:
- name: dl_cache
  host:
    path: /var/lib/cache/llae-dl
- name: docker_sock
  host:
    path: /var/run/docker.sock
steps:
- name: cleanup
  image: alpine
  commands:
    - rm -rf bin/* build/* lib/*
- name: download
  image: build-llae
  pull: never
  volumes:
  - name: dl_cache
    path: /tmp/llae-dl
  environment:
    LLAE_DL_DIR: /tmp/llae-dl
  commands:
    - premake5 download
- name: prepare
  image: build-llae
  pull: never
  volumes:
  - name: dl_cache
    path: /tmp/llae-dl
  environment:
    LLAE_DL_DIR: /tmp/llae-dl
  commands:
    - premake5 unpack
    - premake5 gmake2
- name: build
  image: build-llae
  pull: never
  environment:
  commands:
    - make -C build verbose=1 config=debug
    - make -C build verbose=1 clean
    - make -C build verbose=1 config=release 

- name: clean-for-windows
  image: build-llae
  pull: never
  volumes:
  - name: dl_cache
    path: /tmp/llae-dl
  environment:
    LLAE_DL_DIR: /tmp/llae-dl
  commands:
    - rm -rf bin/* build/* lib/*
    - premake5 download

- name: prepare-windows
  image: build-llae-windows
  pull: never
  volumes:
  - name: dl_cache
    path: /tmp/llae-dl
  environment:
    LLAE_DL_DIR: /tmp/llae-dl
  commands:
    - premake5 unpack
    - premake5 --os=windows gmake2

- name: build-windows
  image: build-llae-windows
  pull: never
  environment:
     TOOLCHAIN: x86_64-w64-mingw32-
     CC: x86_64-w64-mingw32-gcc
     CXX: x86_64-w64-mingw32-g++
     AR: x86_64-w64-mingw32-ar
     LD: x86_64-w64-mingw32-ld
  commands:
   - make -C build verbose=1 config=debug 
   - make -C build verbose=1 clean
   - make -C build verbose=1 config=release 

- name: build-image
  image: docker
  commands: 
    - echo "commit: $DRONE_COMMIT_SHA"
    - docker build -f docker/llae.dockerfile -t llae:latest --build-arg CACHE_BREAKER=$DRONE_COMMIT_SHA .
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
# depends_on:
# - docker-windows