
local _M = {}

local pkgconfig = function(module,var)
	local res,status = os.outputof("pkg-config " .. module .. " --" .. var)
	assert(status==0,"not found package " .. module .. " var " .. var)
	return res
end

local pkgconfig_var = function(module,var)
	local res,status = os.outputof("pkg-config " .. module .. " --variable=" .. var)
	assert(status==0,"not found package " .. module .. " var " .. var)
	return res
end

_M.root = './'

_M.pkgconfig = pkgconfig
_M.pkgconfig_var = pkgconfig

function _M.lib(  )
	project 'llae'
		kind 'StaticLib'
		location 'build'
		targetdir 'lib'
		
		if os.istarget('macosx') then
			includedirs(pkgconfig_var('yajl','prefix')..'/include')
		end

		_M.compile()
		
		files {
			path.join(_M.root,'src','**.cpp'),
			path.join(_M.root,'src','**.h')
		}

		removefiles {
			path.join(_M.root,'src','main.cpp'),
		}
end

function _M.compile(  )
	buildoptions{ 
		pkgconfig('lua-5.3','cflags'),
		pkgconfig('libuv','cflags'),
		pkgconfig('yajl','cflags'),
		pkgconfig('openssl','cflags'),	
	}
	includedirs{
		path.join(_M.root ,'src') 
	}
end

function _M.exe(  )
	_M.compile()
	files {
		path.join(_M.root,'src','main.cpp'),
	}
	_M.link()
end

function _M.link(  )
	linkoptions { 
		pkgconfig('lua-5.3','libs'),
		pkgconfig('libuv','libs'),
		pkgconfig('yajl','libs'),
		pkgconfig('openssl','libs'),
	}
	links {
		'llae'
	}
end

function _M.builddir( )
	local prj = configuration().name
	return path.getabsolute(path.join(_MAIN_SCRIPT_DIR, 'build', prj))
end

local function load_file(fn)
	local fname = path.getabsolute(fn)
	local f = io.open(fname, "rb")
	local s = assert(f:read("*all"))
	f:close()
	return s
end

local function output_script(result, data)
	local length = #data
	buffered.write(result,'\t')
	for i = 1, length do
		buffered.write(result, string.format("0x%02x,", data:byte(i)))
		if (i % 16 == 0) and i~=length then
			buffered.writeln(result)
			buffered.write(result,'\t')
		end
	end
	buffered.writeln(result)
end

function _M.embed( patterns )
	local result = buffered.new()
	buffered.writeln(result, "/* autogenerated embedded scripts */")
	buffered.writeln(result, '#include "lua_state.h"')
	buffered.writeln(result, 'extern "C" {')
	buffered.writeln(result, "#include <lua.h>")
	buffered.writeln(result, "#include <lauxlib.h>")
	buffered.writeln(result, '}')
	buffered.writeln(result, "#include <cstring>")

	local embedded_files = {}
	for _,v in ipairs(patterns) do
		--print('process pattern',v[1])
		local files = os.matchfiles(v[1])
		local baseDir = v[2] 
		for _,f in ipairs(files) do
			local dst_name = baseDir and path.getrelative(baseDir, f) or f
			buffered.writeln(result, "/* " .. dst_name .. " */")
			local id_name = dst_name:gsub('[%.%/]','_')
			buffered.writeln(result, "static const unsigned char " .. id_name .. '[] = {')
			local conent = load_file(f)
			output_script(result,conent)
			buffered.writeln(result,'};')
			table.insert(embedded_files,{
				id = id_name,
				name = dst_name:gsub('[%/]','.'):gsub('%.lua','')
				})
		end
	end
	

	buffered.writeln(result, "")
	buffered.writeln(result, "struct script_t {")
	buffered.writeln(result, "\tconst char* name;")
	buffered.writeln(result, "\tconst unsigned char* content;")
	buffered.writeln(result, "\tsize_t size;")
	buffered.writeln(result, "};")
	buffered.writeln(result, "static const script_t	scripts[] = {")
	for _,v in ipairs(embedded_files) do
		buffered.writeln(result, "\t{")
		buffered.writeln(result, '\t\t"' .. v.name .. '",')
		buffered.writeln(result, '\t\t' .. v.id .. ',')
		buffered.writeln(result, '\t\tsizeof(' .. v.id .. ')')
		buffered.writeln(result, "\t},")
	end
	buffered.writeln(result, "\t{0,0,0}")
	buffered.writeln(result, "};")
	buffered.writeln(result, "")

	buffered.writeln(result, "static int load_script(lua_State* L,const script_t* script) {")
	buffered.writeln(result,[[
	lua_pushstring(L, "$");
	lua_pushstring(L, script->name);
	lua_pushstring(L, ".lua");
	lua_concat(L, 3);
	luaL_loadbuffer(L, (const char*)script->content, script->size, script->name);
	return 1;]])
	buffered.writeln(result, "}")

	buffered.writeln(result, "static int embedded_searcher(lua_State* L) {")
	buffered.writeln(result, [[
	const char *name = luaL_checkstring(L, 1);
	const script_t* s = scripts;
	while (s->name) {
		if (strcmp(s->name,name)==0){
			return load_script(L,s);
		}
		++s;
	}
	lua_pushstring(L,"embedded");
	return 1;]])
	buffered.writeln(result, "}")

	buffered.writeln(result, "int attach_embedded_scripts(Lua::StateRef& lua) {")
	buffered.writeln(result, [[
	lua.getglobal("table");
	lua.getfield(-1,"insert");
	lua.remove(-2);
	lua.getglobal("package");
	lua.getfield(-1,"searchers");
	lua.remove(-2);
	lua.pushinteger(1);
	lua.pushcclosure(embedded_searcher,0);
	lua.call(3,0);
	return 0;]])
	buffered.writeln(result, "}")
	
	local dir = _M.builddir()
	os.mkdir(dir)
	local scriptsFile = path.join( dir, "embed_scripts.cpp")

	local output = buffered.tostring(result)

	files { scriptsFile }

	local f, err = os.writefile_ifnotequal(output, scriptsFile);
	if (f < 0) then
		error(err, 0)
	elseif (f > 0) then
		printf("Generated %s...", path.getrelative(os.getcwd(), scriptsFile))
	end
end

return _M